/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.www.marketing.events.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.www.marketing.events.model.MarketingEventSponsor;
import com.liferay.osb.www.marketing.events.model.MarketingEventSponsorModel;
import com.liferay.osb.www.marketing.events.model.MarketingEventSponsorSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the MarketingEventSponsor service. Represents a row in the &quot;OSB_MarketingEventSponsor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MarketingEventSponsorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarketingEventSponsorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarketingEventSponsorImpl
 * @see MarketingEventSponsor
 * @see MarketingEventSponsorModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MarketingEventSponsorModelImpl extends BaseModelImpl<MarketingEventSponsor>
	implements MarketingEventSponsorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a marketing event sponsor model instance should use the {@link MarketingEventSponsor} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_MarketingEventSponsor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "marketingEventSponsorId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "marketingEventId", Types.BIGINT },
			{ "marketingEventSponsorLevelId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "imageFileEntryId", Types.BIGINT },
			{ "url", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("marketingEventSponsorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("marketingEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("marketingEventSponsorLevelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_MarketingEventSponsor (marketingEventSponsorId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,marketingEventId LONG,marketingEventSponsorLevelId LONG,name VARCHAR(75) null,description STRING null,imageFileEntryId LONG,url VARCHAR(150) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_MarketingEventSponsor";
	public static final String ORDER_BY_JPQL = " ORDER BY marketingEventSponsor.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_MarketingEventSponsor.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.www.marketing.events.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.www.marketing.events.model.MarketingEventSponsor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.www.marketing.events.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.www.marketing.events.model.MarketingEventSponsor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.www.marketing.events.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.www.marketing.events.model.MarketingEventSponsor"),
			true);
	public static final long MARKETINGEVENTID_COLUMN_BITMASK = 1L;
	public static final long MARKETINGEVENTSPONSORLEVELID_COLUMN_BITMASK = 2L;
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MarketingEventSponsor toModel(
		MarketingEventSponsorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MarketingEventSponsor model = new MarketingEventSponsorImpl();

		model.setMarketingEventSponsorId(soapModel.getMarketingEventSponsorId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMarketingEventId(soapModel.getMarketingEventId());
		model.setMarketingEventSponsorLevelId(soapModel.getMarketingEventSponsorLevelId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setImageFileEntryId(soapModel.getImageFileEntryId());
		model.setUrl(soapModel.getUrl());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MarketingEventSponsor> toModels(
		MarketingEventSponsorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MarketingEventSponsor> models = new ArrayList<MarketingEventSponsor>(soapModels.length);

		for (MarketingEventSponsorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.www.marketing.events.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.www.marketing.events.model.MarketingEventSponsor"));

	public MarketingEventSponsorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _marketingEventSponsorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMarketingEventSponsorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _marketingEventSponsorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MarketingEventSponsor.class;
	}

	@Override
	public String getModelClassName() {
		return MarketingEventSponsor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("marketingEventSponsorId", getMarketingEventSponsorId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("marketingEventId", getMarketingEventId());
		attributes.put("marketingEventSponsorLevelId",
			getMarketingEventSponsorLevelId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("imageFileEntryId", getImageFileEntryId());
		attributes.put("url", getUrl());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long marketingEventSponsorId = (Long)attributes.get(
				"marketingEventSponsorId");

		if (marketingEventSponsorId != null) {
			setMarketingEventSponsorId(marketingEventSponsorId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long marketingEventId = (Long)attributes.get("marketingEventId");

		if (marketingEventId != null) {
			setMarketingEventId(marketingEventId);
		}

		Long marketingEventSponsorLevelId = (Long)attributes.get(
				"marketingEventSponsorLevelId");

		if (marketingEventSponsorLevelId != null) {
			setMarketingEventSponsorLevelId(marketingEventSponsorLevelId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long imageFileEntryId = (Long)attributes.get("imageFileEntryId");

		if (imageFileEntryId != null) {
			setImageFileEntryId(imageFileEntryId);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}
	}

	@JSON
	@Override
	public long getMarketingEventSponsorId() {
		return _marketingEventSponsorId;
	}

	@Override
	public void setMarketingEventSponsorId(long marketingEventSponsorId) {
		_marketingEventSponsorId = marketingEventSponsorId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMarketingEventId() {
		return _marketingEventId;
	}

	@Override
	public void setMarketingEventId(long marketingEventId) {
		_columnBitmask |= MARKETINGEVENTID_COLUMN_BITMASK;

		if (!_setOriginalMarketingEventId) {
			_setOriginalMarketingEventId = true;

			_originalMarketingEventId = _marketingEventId;
		}

		_marketingEventId = marketingEventId;
	}

	public long getOriginalMarketingEventId() {
		return _originalMarketingEventId;
	}

	@JSON
	@Override
	public long getMarketingEventSponsorLevelId() {
		return _marketingEventSponsorLevelId;
	}

	@Override
	public void setMarketingEventSponsorLevelId(
		long marketingEventSponsorLevelId) {
		_columnBitmask |= MARKETINGEVENTSPONSORLEVELID_COLUMN_BITMASK;

		if (!_setOriginalMarketingEventSponsorLevelId) {
			_setOriginalMarketingEventSponsorLevelId = true;

			_originalMarketingEventSponsorLevelId = _marketingEventSponsorLevelId;
		}

		_marketingEventSponsorLevelId = marketingEventSponsorLevelId;
	}

	public long getOriginalMarketingEventSponsorLevelId() {
		return _originalMarketingEventSponsorLevelId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescription(), languageId,
			useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setDescription(String description, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getDefault());
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale) {
		if (descriptionMap == null) {
			return;
		}

		setDescription(LocalizationUtil.updateLocalization(descriptionMap,
				getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public long getImageFileEntryId() {
		return _imageFileEntryId;
	}

	@Override
	public void setImageFileEntryId(long imageFileEntryId) {
		_imageFileEntryId = imageFileEntryId;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MarketingEventSponsor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDescription();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(MarketingEventSponsor.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(getDescription(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public MarketingEventSponsor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MarketingEventSponsor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MarketingEventSponsorImpl marketingEventSponsorImpl = new MarketingEventSponsorImpl();

		marketingEventSponsorImpl.setMarketingEventSponsorId(getMarketingEventSponsorId());
		marketingEventSponsorImpl.setUserId(getUserId());
		marketingEventSponsorImpl.setUserName(getUserName());
		marketingEventSponsorImpl.setCreateDate(getCreateDate());
		marketingEventSponsorImpl.setModifiedDate(getModifiedDate());
		marketingEventSponsorImpl.setMarketingEventId(getMarketingEventId());
		marketingEventSponsorImpl.setMarketingEventSponsorLevelId(getMarketingEventSponsorLevelId());
		marketingEventSponsorImpl.setName(getName());
		marketingEventSponsorImpl.setDescription(getDescription());
		marketingEventSponsorImpl.setImageFileEntryId(getImageFileEntryId());
		marketingEventSponsorImpl.setUrl(getUrl());

		marketingEventSponsorImpl.resetOriginalValues();

		return marketingEventSponsorImpl;
	}

	@Override
	public int compareTo(MarketingEventSponsor marketingEventSponsor) {
		int value = 0;

		value = getName().compareTo(marketingEventSponsor.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MarketingEventSponsor)) {
			return false;
		}

		MarketingEventSponsor marketingEventSponsor = (MarketingEventSponsor)obj;

		long primaryKey = marketingEventSponsor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MarketingEventSponsorModelImpl marketingEventSponsorModelImpl = this;

		marketingEventSponsorModelImpl._setModifiedDate = false;

		marketingEventSponsorModelImpl._originalMarketingEventId = marketingEventSponsorModelImpl._marketingEventId;

		marketingEventSponsorModelImpl._setOriginalMarketingEventId = false;

		marketingEventSponsorModelImpl._originalMarketingEventSponsorLevelId = marketingEventSponsorModelImpl._marketingEventSponsorLevelId;

		marketingEventSponsorModelImpl._setOriginalMarketingEventSponsorLevelId = false;

		marketingEventSponsorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MarketingEventSponsor> toCacheModel() {
		MarketingEventSponsorCacheModel marketingEventSponsorCacheModel = new MarketingEventSponsorCacheModel();

		marketingEventSponsorCacheModel.marketingEventSponsorId = getMarketingEventSponsorId();

		marketingEventSponsorCacheModel.userId = getUserId();

		marketingEventSponsorCacheModel.userName = getUserName();

		String userName = marketingEventSponsorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			marketingEventSponsorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			marketingEventSponsorCacheModel.createDate = createDate.getTime();
		}
		else {
			marketingEventSponsorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			marketingEventSponsorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			marketingEventSponsorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		marketingEventSponsorCacheModel.marketingEventId = getMarketingEventId();

		marketingEventSponsorCacheModel.marketingEventSponsorLevelId = getMarketingEventSponsorLevelId();

		marketingEventSponsorCacheModel.name = getName();

		String name = marketingEventSponsorCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			marketingEventSponsorCacheModel.name = null;
		}

		marketingEventSponsorCacheModel.description = getDescription();

		String description = marketingEventSponsorCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			marketingEventSponsorCacheModel.description = null;
		}

		marketingEventSponsorCacheModel.imageFileEntryId = getImageFileEntryId();

		marketingEventSponsorCacheModel.url = getUrl();

		String url = marketingEventSponsorCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			marketingEventSponsorCacheModel.url = null;
		}

		return marketingEventSponsorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{marketingEventSponsorId=");
		sb.append(getMarketingEventSponsorId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", marketingEventId=");
		sb.append(getMarketingEventId());
		sb.append(", marketingEventSponsorLevelId=");
		sb.append(getMarketingEventSponsorLevelId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", imageFileEntryId=");
		sb.append(getImageFileEntryId());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.osb.www.marketing.events.model.MarketingEventSponsor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>marketingEventSponsorId</column-name><column-value><![CDATA[");
		sb.append(getMarketingEventSponsorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketingEventId</column-name><column-value><![CDATA[");
		sb.append(getMarketingEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketingEventSponsorLevelId</column-name><column-value><![CDATA[");
		sb.append(getMarketingEventSponsorLevelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageFileEntryId</column-name><column-value><![CDATA[");
		sb.append(getImageFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MarketingEventSponsor.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MarketingEventSponsor.class
		};
	private long _marketingEventSponsorId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _marketingEventId;
	private long _originalMarketingEventId;
	private boolean _setOriginalMarketingEventId;
	private long _marketingEventSponsorLevelId;
	private long _originalMarketingEventSponsorLevelId;
	private boolean _setOriginalMarketingEventSponsorLevelId;
	private String _name;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private long _imageFileEntryId;
	private String _url;
	private long _columnBitmask;
	private MarketingEventSponsor _escapedModel;
}