/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.www.marketing.events.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the MarketingEventSponsorLevel service. Represents a row in the &quot;OSB_MarketingEventSponsorLevel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorLevelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorLevelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarketingEventSponsorLevel
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorLevelImpl
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorLevelModelImpl
 * @generated
 */
@ProviderType
public interface MarketingEventSponsorLevelModel extends BaseModel<MarketingEventSponsorLevel>,
	LocalizedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a marketing event sponsor level model instance should use the {@link MarketingEventSponsorLevel} interface instead.
	 */

	/**
	 * Returns the primary key of this marketing event sponsor level.
	 *
	 * @return the primary key of this marketing event sponsor level
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this marketing event sponsor level.
	 *
	 * @param primaryKey the primary key of this marketing event sponsor level
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marketing event sponsor level ID of this marketing event sponsor level.
	 *
	 * @return the marketing event sponsor level ID of this marketing event sponsor level
	 */
	public long getMarketingEventSponsorLevelId();

	/**
	 * Sets the marketing event sponsor level ID of this marketing event sponsor level.
	 *
	 * @param marketingEventSponsorLevelId the marketing event sponsor level ID of this marketing event sponsor level
	 */
	public void setMarketingEventSponsorLevelId(
		long marketingEventSponsorLevelId);

	/**
	 * Returns the user ID of this marketing event sponsor level.
	 *
	 * @return the user ID of this marketing event sponsor level
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this marketing event sponsor level.
	 *
	 * @param userId the user ID of this marketing event sponsor level
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this marketing event sponsor level.
	 *
	 * @return the user uuid of this marketing event sponsor level
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this marketing event sponsor level.
	 *
	 * @param userUuid the user uuid of this marketing event sponsor level
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this marketing event sponsor level.
	 *
	 * @return the user name of this marketing event sponsor level
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this marketing event sponsor level.
	 *
	 * @param userName the user name of this marketing event sponsor level
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this marketing event sponsor level.
	 *
	 * @return the create date of this marketing event sponsor level
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this marketing event sponsor level.
	 *
	 * @param createDate the create date of this marketing event sponsor level
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this marketing event sponsor level.
	 *
	 * @return the modified date of this marketing event sponsor level
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this marketing event sponsor level.
	 *
	 * @param modifiedDate the modified date of this marketing event sponsor level
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marketing event ID of this marketing event sponsor level.
	 *
	 * @return the marketing event ID of this marketing event sponsor level
	 */
	public long getMarketingEventId();

	/**
	 * Sets the marketing event ID of this marketing event sponsor level.
	 *
	 * @param marketingEventId the marketing event ID of this marketing event sponsor level
	 */
	public void setMarketingEventId(long marketingEventId);

	/**
	 * Returns the name of this marketing event sponsor level.
	 *
	 * @return the name of this marketing event sponsor level
	 */
	public String getName();

	/**
	 * Returns the localized name of this marketing event sponsor level in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this marketing event sponsor level
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this marketing event sponsor level in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this marketing event sponsor level. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this marketing event sponsor level in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this marketing event sponsor level
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this marketing event sponsor level in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this marketing event sponsor level
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this marketing event sponsor level.
	 *
	 * @return the locales and localized names of this marketing event sponsor level
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this marketing event sponsor level.
	 *
	 * @param name the name of this marketing event sponsor level
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this marketing event sponsor level in the language.
	 *
	 * @param name the localized name of this marketing event sponsor level
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this marketing event sponsor level in the language, and sets the default locale.
	 *
	 * @param name the localized name of this marketing event sponsor level
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this marketing event sponsor level from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this marketing event sponsor level
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this marketing event sponsor level from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this marketing event sponsor level
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the priority of this marketing event sponsor level.
	 *
	 * @return the priority of this marketing event sponsor level
	 */
	public int getPriority();

	/**
	 * Sets the priority of this marketing event sponsor level.
	 *
	 * @param priority the priority of this marketing event sponsor level
	 */
	public void setPriority(int priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(MarketingEventSponsorLevel marketingEventSponsorLevel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MarketingEventSponsorLevel> toCacheModel();

	@Override
	public MarketingEventSponsorLevel toEscapedModel();

	@Override
	public MarketingEventSponsorLevel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}