/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.www.marketing.events.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the MarketingEventSponsor service. Represents a row in the &quot;OSB_MarketingEventSponsor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarketingEventSponsor
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorImpl
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSponsorModelImpl
 * @generated
 */
@ProviderType
public interface MarketingEventSponsorModel extends BaseModel<MarketingEventSponsor>,
	LocalizedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a marketing event sponsor model instance should use the {@link MarketingEventSponsor} interface instead.
	 */

	/**
	 * Returns the primary key of this marketing event sponsor.
	 *
	 * @return the primary key of this marketing event sponsor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this marketing event sponsor.
	 *
	 * @param primaryKey the primary key of this marketing event sponsor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marketing event sponsor ID of this marketing event sponsor.
	 *
	 * @return the marketing event sponsor ID of this marketing event sponsor
	 */
	public long getMarketingEventSponsorId();

	/**
	 * Sets the marketing event sponsor ID of this marketing event sponsor.
	 *
	 * @param marketingEventSponsorId the marketing event sponsor ID of this marketing event sponsor
	 */
	public void setMarketingEventSponsorId(long marketingEventSponsorId);

	/**
	 * Returns the user ID of this marketing event sponsor.
	 *
	 * @return the user ID of this marketing event sponsor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this marketing event sponsor.
	 *
	 * @param userId the user ID of this marketing event sponsor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this marketing event sponsor.
	 *
	 * @return the user uuid of this marketing event sponsor
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this marketing event sponsor.
	 *
	 * @param userUuid the user uuid of this marketing event sponsor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this marketing event sponsor.
	 *
	 * @return the user name of this marketing event sponsor
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this marketing event sponsor.
	 *
	 * @param userName the user name of this marketing event sponsor
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this marketing event sponsor.
	 *
	 * @return the create date of this marketing event sponsor
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this marketing event sponsor.
	 *
	 * @param createDate the create date of this marketing event sponsor
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this marketing event sponsor.
	 *
	 * @return the modified date of this marketing event sponsor
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this marketing event sponsor.
	 *
	 * @param modifiedDate the modified date of this marketing event sponsor
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marketing event ID of this marketing event sponsor.
	 *
	 * @return the marketing event ID of this marketing event sponsor
	 */
	public long getMarketingEventId();

	/**
	 * Sets the marketing event ID of this marketing event sponsor.
	 *
	 * @param marketingEventId the marketing event ID of this marketing event sponsor
	 */
	public void setMarketingEventId(long marketingEventId);

	/**
	 * Returns the marketing event sponsor level ID of this marketing event sponsor.
	 *
	 * @return the marketing event sponsor level ID of this marketing event sponsor
	 */
	public long getMarketingEventSponsorLevelId();

	/**
	 * Sets the marketing event sponsor level ID of this marketing event sponsor.
	 *
	 * @param marketingEventSponsorLevelId the marketing event sponsor level ID of this marketing event sponsor
	 */
	public void setMarketingEventSponsorLevelId(
		long marketingEventSponsorLevelId);

	/**
	 * Returns the name of this marketing event sponsor.
	 *
	 * @return the name of this marketing event sponsor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this marketing event sponsor.
	 *
	 * @param name the name of this marketing event sponsor
	 */
	public void setName(String name);

	/**
	 * Returns the description of this marketing event sponsor.
	 *
	 * @return the description of this marketing event sponsor
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this marketing event sponsor in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this marketing event sponsor
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this marketing event sponsor in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this marketing event sponsor. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this marketing event sponsor in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this marketing event sponsor
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this marketing event sponsor in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this marketing event sponsor
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this marketing event sponsor.
	 *
	 * @return the locales and localized descriptions of this marketing event sponsor
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this marketing event sponsor.
	 *
	 * @param description the description of this marketing event sponsor
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this marketing event sponsor in the language.
	 *
	 * @param description the localized description of this marketing event sponsor
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this marketing event sponsor in the language, and sets the default locale.
	 *
	 * @param description the localized description of this marketing event sponsor
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this marketing event sponsor from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this marketing event sponsor
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this marketing event sponsor from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this marketing event sponsor
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the image file entry ID of this marketing event sponsor.
	 *
	 * @return the image file entry ID of this marketing event sponsor
	 */
	public long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this marketing event sponsor.
	 *
	 * @param imageFileEntryId the image file entry ID of this marketing event sponsor
	 */
	public void setImageFileEntryId(long imageFileEntryId);

	/**
	 * Returns the url of this marketing event sponsor.
	 *
	 * @return the url of this marketing event sponsor
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this marketing event sponsor.
	 *
	 * @param url the url of this marketing event sponsor
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(MarketingEventSponsor marketingEventSponsor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MarketingEventSponsor> toCacheModel();

	@Override
	public MarketingEventSponsor toEscapedModel();

	@Override
	public MarketingEventSponsor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}