/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.www.marketing.events.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SocialLink service. Represents a row in the &quot;OSB_SocialLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.www.marketing.events.model.impl.SocialLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.www.marketing.events.model.impl.SocialLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialLink
 * @see com.liferay.osb.www.marketing.events.model.impl.SocialLinkImpl
 * @see com.liferay.osb.www.marketing.events.model.impl.SocialLinkModelImpl
 * @generated
 */
@ProviderType
public interface SocialLinkModel extends BaseModel<SocialLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a social link model instance should use the {@link SocialLink} interface instead.
	 */

	/**
	 * Returns the primary key of this social link.
	 *
	 * @return the primary key of this social link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this social link.
	 *
	 * @param primaryKey the primary key of this social link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the social link ID of this social link.
	 *
	 * @return the social link ID of this social link
	 */
	public long getSocialLinkId();

	/**
	 * Sets the social link ID of this social link.
	 *
	 * @param socialLinkId the social link ID of this social link
	 */
	public void setSocialLinkId(long socialLinkId);

	/**
	 * Returns the user ID of this social link.
	 *
	 * @return the user ID of this social link
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this social link.
	 *
	 * @param userId the user ID of this social link
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this social link.
	 *
	 * @return the user uuid of this social link
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this social link.
	 *
	 * @param userUuid the user uuid of this social link
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this social link.
	 *
	 * @return the user name of this social link
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this social link.
	 *
	 * @param userName the user name of this social link
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this social link.
	 *
	 * @return the create date of this social link
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this social link.
	 *
	 * @param createDate the create date of this social link
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this social link.
	 *
	 * @return the modified date of this social link
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this social link.
	 *
	 * @param modifiedDate the modified date of this social link
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marketing event user ID of this social link.
	 *
	 * @return the marketing event user ID of this social link
	 */
	public long getMarketingEventUserId();

	/**
	 * Sets the marketing event user ID of this social link.
	 *
	 * @param marketingEventUserId the marketing event user ID of this social link
	 */
	public void setMarketingEventUserId(long marketingEventUserId);

	/**
	 * Returns the marketing event user uuid of this social link.
	 *
	 * @return the marketing event user uuid of this social link
	 */
	public String getMarketingEventUserUuid();

	/**
	 * Sets the marketing event user uuid of this social link.
	 *
	 * @param marketingEventUserUuid the marketing event user uuid of this social link
	 */
	public void setMarketingEventUserUuid(String marketingEventUserUuid);

	/**
	 * Returns the social link type ID of this social link.
	 *
	 * @return the social link type ID of this social link
	 */
	public long getSocialLinkTypeId();

	/**
	 * Sets the social link type ID of this social link.
	 *
	 * @param socialLinkTypeId the social link type ID of this social link
	 */
	public void setSocialLinkTypeId(long socialLinkTypeId);

	/**
	 * Returns the url of this social link.
	 *
	 * @return the url of this social link
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this social link.
	 *
	 * @param url the url of this social link
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SocialLink socialLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SocialLink> toCacheModel();

	@Override
	public SocialLink toEscapedModel();

	@Override
	public SocialLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}