/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.www.marketing.events.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MarketingEventSessionRoom service. Represents a row in the &quot;OSB_MarketingEventSessionRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSessionRoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.www.marketing.events.model.impl.MarketingEventSessionRoomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarketingEventSessionRoom
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSessionRoomImpl
 * @see com.liferay.osb.www.marketing.events.model.impl.MarketingEventSessionRoomModelImpl
 * @generated
 */
@ProviderType
public interface MarketingEventSessionRoomModel extends BaseModel<MarketingEventSessionRoom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a marketing event session room model instance should use the {@link MarketingEventSessionRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this marketing event session room.
	 *
	 * @return the primary key of this marketing event session room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this marketing event session room.
	 *
	 * @param primaryKey the primary key of this marketing event session room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marketing event session room ID of this marketing event session room.
	 *
	 * @return the marketing event session room ID of this marketing event session room
	 */
	public long getMarketingEventSessionRoomId();

	/**
	 * Sets the marketing event session room ID of this marketing event session room.
	 *
	 * @param marketingEventSessionRoomId the marketing event session room ID of this marketing event session room
	 */
	public void setMarketingEventSessionRoomId(long marketingEventSessionRoomId);

	/**
	 * Returns the create date of this marketing event session room.
	 *
	 * @return the create date of this marketing event session room
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this marketing event session room.
	 *
	 * @param createDate the create date of this marketing event session room
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this marketing event session room.
	 *
	 * @return the modified date of this marketing event session room
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this marketing event session room.
	 *
	 * @param modifiedDate the modified date of this marketing event session room
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marketing event ID of this marketing event session room.
	 *
	 * @return the marketing event ID of this marketing event session room
	 */
	public long getMarketingEventId();

	/**
	 * Sets the marketing event ID of this marketing event session room.
	 *
	 * @param marketingEventId the marketing event ID of this marketing event session room
	 */
	public void setMarketingEventId(long marketingEventId);

	/**
	 * Returns the name of this marketing event session room.
	 *
	 * @return the name of this marketing event session room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this marketing event session room.
	 *
	 * @param name the name of this marketing event session room
	 */
	public void setName(String name);

	/**
	 * Returns the image file entry ID of this marketing event session room.
	 *
	 * @return the image file entry ID of this marketing event session room
	 */
	public long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this marketing event session room.
	 *
	 * @param imageFileEntryId the image file entry ID of this marketing event session room
	 */
	public void setImageFileEntryId(long imageFileEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MarketingEventSessionRoom marketingEventSessionRoom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MarketingEventSessionRoom> toCacheModel();

	@Override
	public MarketingEventSessionRoom toEscapedModel();

	@Override
	public MarketingEventSessionRoom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}